### ISSUE TITLE
getting error  :  can not include <font-awesome/check_circle>

### ISSUE THREAD

**Issue by hillpates123** [joelparkerhenderson/plantuml-examples#2]
when trying  online at https://www.plantuml.com/plantuml/uml

getting this error

**Comment by joelparkerhenderson** [comment]
For the online renderer, can you try providing a path?

For example, try prepending "tupadr3" to the path, like this:

```plantuml
@startuml
!include <tupadr3/font-awesome/check_circle>
rectangle "<$check_circle>"
@enduml
```

Does that succeed for you?

**Comment by joelparkerhenderson** [comment]
I haven't seen a reply from you for a couple weeks, so I'll close this issue for now. Feel free to reopen it if you still need help.
